### ISSUE TITLE
Suggestion: Use proxychains to run bruteforce

### ISSUE THREAD

**Issue by Ubuntufanboy** [Sarthak2143/GmailBruteforce#1]
Pros:

- New ip adresses so can't get blocked
- Harder to trace

Cons:
- Loss of speed
- Proxys might be blocked by google

**Comment by Sarthak2143** [comment]
Have you checked the official site of the tool? Because I stated there that this tool will no longer work due to new Google policies.
I had this idea in my TODO for a while but its of no use now.
I appreciate that you took time to suggest.
